const std = @import("std");
const zephyr = @import("zephyr");

pub fn main(init: std.process.Init) !void {
    const gpa = init.arena.allocator();
    const args = try init.minimal.args.toSlice(gpa);
    if (args.len != 3) std.process.fatal("usage: vk_generator <vk.xml path> <output vk.zig path>", .{});

    const vk_xml_path = args[1];
    const output_path = args[2];

    const xml = try std.Io.Dir.cwd().readFileAlloc(init.io, vk_xml_path, gpa, .limited(64 * 1024 * 1024));

    var registry = try zephyr.registry.parse(gpa, xml);
    defer registry.deinit();

    var out: std.ArrayList(u8) = .empty;
    try out.appendSlice(gpa, "// AUTO-GENERATED by modules/zephyr/src/vk_generator -- DO NOT EDIT\n\n");
    try out.appendSlice(gpa, "const std = @import(\"std\");\n\n");
    try out.appendSlice(gpa, @embedFile("preamble.vk.zig"));
    try out.appendSlice(gpa, "\n");

    try zephyr.emit.write(gpa, &registry, &out);

    try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = output_path, .data = out.items });
}
