const std = @import("std");
const xml_scan = @import("xml_scan.zig");

/// Names already declared by preamble.vk.zig; seeded defensively so a future vk.xml
/// addition can never silently collide with a hand-written wrapper.
const reserved_names = [_][]const u8{
    "Error",
    "check_result",
    "vmaCreateAllocator",
    "vmaCreateImage",
    "getPhysicalDeviceQueueFamilyProperties",
    "getPhysicalDeviceQueueFamilyProperties2",
};

pub fn main(init: std.process.Init) !void {
    const gpa = init.arena.allocator();
    const args = try init.minimal.args.toSlice(gpa);
    if (args.len != 3) std.process.fatal("usage: vk_generator <vk.xml path> <output vk.zig path>", .{});

    const vk_xml_path = args[1];
    const output_path = args[2];

    const xml = try std.Io.Dir.cwd().readFileAlloc(init.io, vk_xml_path, gpa, .limited(64 * 1024 * 1024));
    const commands_block = xml_scan.extractBlock(xml, "<commands", "</commands>");

    var out: std.ArrayList(u8) = .empty;
    try out.appendSlice(gpa, "// AUTO-GENERATED by tools/vk_generator -- DO NOT EDIT\n\n");
    try out.appendSlice(gpa, @embedFile("preamble.vk.zig"));
    try out.appendSlice(gpa, "\n");

    var seen = std.StringHashMap(void).init(gpa);
    for (reserved_names) |name| try seen.put(name, {});

    var name_buf: [256]u8 = undefined;
    var it = xml_scan.CommandIterator{ .xml = commands_block };
    while (try it.next(gpa)) |cmd| {
        const zig_name = xml_scan.zigName(&name_buf, cmd.c_name);
        if (seen.contains(zig_name)) {
            std.log.warn("vk_generator: skipping duplicate generated name '{s}' ({s})", .{ zig_name, cmd.c_name });
            continue;
        }
        try seen.put(try gpa.dupe(u8, zig_name), {});

        try out.print(gpa, "pub fn {s}(", .{zig_name});
        for (cmd.params) |p| try out.print(gpa, "@\"{s}\": anytype, ", .{p});
        try out.print(gpa, ") Error!void {{\n    const result = c.{s}(", .{cmd.c_name});
        for (cmd.params) |p| try out.print(gpa, "@\"{s}\", ", .{p});
        try out.appendSlice(gpa, ");\n    try check_result(result);\n}\n\n");
    }

    try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = output_path, .data = out.items });
}
